= Streams

A http://golang.org/[Go] port of Java streams, that only handles single threaded sequential data

* Stream uses interface{} for elements
* Stream is based on goiter.Iter to iterate the elements that are the source of the stream
* Each struct has a pair of constructor functions:
** Of(...) constructs a Stream of hard-coded elements
** OfIter(*goiter.Iter) constructs a Stream, from an existing Iter
** Stream is an Iterable, so OfIter can be passed an Iter constructed with goiter.OfIterables(Stream1, Stream2, ...), which will effectively concatenate Streams
* Average and Sum functions require elements to be convertible to float64
* All operations declared in Stream
* Instead of separate collectors use GroupBy, ToMap, ToSlice, ToSliceOf
* Stream have some methods Java doesn't
** Duplicate is the opposite of distinct, only returns duplicate elements
** GroupBy takes a func that converts an element into an interface{} key and returns a map[interface{}][]<element type>. All elements that have the same key are mapped into the same slice.
** ToMap takes a func that converts an element into an interface{} key and an interface{} value to put into a map. If multiple elements are mapped to the same key, they overwrite the value for the key.
** ToSlice collects all the elements into a slice
** ToSliceOf is like ToSlice, but returns a typed slice   
* Sorted and ReverseSorted return a new sorted stream
