// SPDX-License-Identifier: Apache-2.0
:doctype: article

= Streams

A http://golang.org/[Go] port of Java streams, with a single implementation and a simplified method of parallel processing

* Stream uses interface{} for elements
* Stream is based on goiter.Iter to iterate the elements that are the source of the stream
* Each struct has a pair of constructor functions:
** Of(...) constructs a Stream of hard-coded elements
** OfIter(*goiter.Iter) constructs a Stream, from an existing Iter
** Stream is an Iterable, so OfIter can be passed an Iter constructed with goiter.OfIterables(Stream1, Stream2, ...), which will effectively concatenate Streams
* Average and Sum functions require elements to be convertible to float64
* Instead of separate collectors use GroupBy, ToMap, ToSlice, ToSliceOf
* Stream have some methods Java doesn't
** Duplicate is the opposite of distinct, only returns duplicate elements
** GroupBy takes a func that converts an element into an interface{} key and returns a map[interface{}][]<element type>. All elements that have the same key are mapped into the same slice.
** ToMap takes a func that converts an element into an interface{} key and an interface{} value to put into a map. If multiple elements are mapped to the same key, they overwrite the value for the key.
** ToSlice collects all the elements into a slice
** ToSliceOf is like ToSlice, but returns a typed slice   
* Sorted and ReverseSorted return a new sorted stream

Example code (take from unit tests):

....
// Filter using a func with type interface{}, requires type assertions
fn := func(element interface{}) bool { return element.(int) < 3 }    
s = Of(1, 2, 3)
assert.Equal(t, []interface{}{1, 2}, s.Filter(fn).ToSlice())

// Filter using a typed func, no type assertions
fn2 := FilterFunc(func(element int) bool { return element < 3 })
s = Of(1, 2, 3)
assert.Equal(t, []int{1, 2}, s.Filter(fn2).ToSliceOf(0))
....
